rvm:
  - 1.9.3
  - 2.0.0
  - 2.1

bundler_args: --jobs 7

branches:
  only:
    - master

env:
  - USE_SYSTEM_GECODE=1

before_install:
  - sudo apt-get -y -qq install libgecode-dev

script:
  - bundle exec rake travis:ci